#!/usr/bin/env node
/**
 * Transform an FModel export of the crystal cards DataTable
 * (DT_Crystal_Cards_Skills) into:
 *
 *   extraction/out/cards.extracted.json  — flattened per-row data (full detail,
 *     gitignored; the input for designing the effect mapping)
 *   extraction/out/cardRegistry.draft.js — draft CARD_REGISTRY entries in the
 *     shape src/utils/skillTreeRegistry.js expects
 *
 * The table schema is unknown until the first export, so flattening is
 * generic: nested UE structs become dotted keys with primitive values, and
 * name/description-ish fields are picked up heuristically for the draft.
 *
 * Usage:
 *   node extraction/transform-cards.mjs path/to/DT_Crystal_Cards_Skills.json
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const SCRIPT_DIR = path.dirname(fileURLToPath(import.meta.url));
const OUT_DIR = path.join(SCRIPT_DIR, 'out');

const filePath = process.argv[2];
if (!filePath) {
  console.error('Usage: node extraction/transform-cards.mjs <fmodel-export.json>');
  process.exit(1);
}

const raw = JSON.parse(fs.readFileSync(filePath, 'utf8'));

function findTable(data) {
  const objects = Array.isArray(data) ? data : [data];
  return objects.find((o) => o && typeof o === 'object' && o.Rows && typeof o.Rows === 'object')
    ?? (!Array.isArray(data) ? { Name: '(top-level)', Rows: data } : null);
}

/**
 * Flatten a UE-export value tree into dotted primitive keys.
 * Collapses common FModel wrapper shapes:
 *   { "TagName": "X" }            → "X"           (gameplay tags)
 *   { "ObjectName": "...", ... }  → ObjectName    (object refs)
 *   { "Key": "...", "SourceString": "..." } → SourceString (FText)
 */
function flatten(value, prefix, out) {
  if (value === null || value === undefined) return;
  if (typeof value !== 'object') {
    out[prefix] = value;
    return;
  }
  if (Array.isArray(value)) {
    value.forEach((v, i) => flatten(v, `${prefix}[${i}]`, out));
    return;
  }
  const keys = Object.keys(value);
  if (keys.length === 1 && keys[0] === 'TagName') {
    out[prefix] = value.TagName;
    return;
  }
  if (typeof value.ObjectName === 'string' && keys.length <= 3) {
    out[prefix] = value.ObjectName;
    return;
  }
  if (typeof value.SourceString === 'string') {
    out[prefix] = value.SourceString;
    return;
  }
  for (const key of keys) {
    flatten(value[key], prefix ? `${prefix}.${key}` : key, out);
  }
}

/** Heuristic: find the first flattened key whose name suggests a display field. */
function pickField(flat, patterns) {
  for (const [key, value] of Object.entries(flat)) {
    if (typeof value !== 'string' || !value) continue;
    if (patterns.some((p) => p.test(key))) return value;
  }
  return null;
}

const table = findTable(raw);
if (!table) {
  console.error('No DataTable-shaped object found in this export.');
  process.exit(1);
}

const extracted = {};
const draftEntries = [];

for (const [rowName, row] of Object.entries(table.Rows)) {
  const flat = {};
  flatten(row, '', flat);
  extracted[rowName] = flat;

  const m = rowName.match(/^CARD(\d+)(?:_(\d+))?$/i);
  const family = m ? Number(m[1]) : null;
  const variant = m && m[2] !== undefined ? Number(m[2]) : null;

  const displayName = pickField(flat, [/displayname/i, /\bname\b/i, /title/i])
    ?? (family !== null ? `Card ${family}${variant !== null ? `-${variant}` : ''}` : rowName);
  const description = pickField(flat, [/description/i, /tooltip/i, /\bdesc\b/i]);

  const entry = {
    rowName,
    family,
    variant,
    name: displayName,
    ...(description ? { description } : {}),
    maxLevel: 6,
    effects: [], // TODO: map from cards.extracted.json once the schema is known
  };
  draftEntries.push(entry);
}

fs.mkdirSync(OUT_DIR, { recursive: true });

const extractedPath = path.join(OUT_DIR, 'cards.extracted.json');
fs.writeFileSync(extractedPath, JSON.stringify(extracted, null, 2));

const draftPath = path.join(OUT_DIR, 'cardRegistry.draft.js');
const draftBody = draftEntries
  .map((e) => `  '${e.rowName}': ${JSON.stringify(e)},`)
  .join('\n');
fs.writeFileSync(
  draftPath,
  `// Draft CARD_REGISTRY generated by extraction/transform-cards.mjs\n` +
  `// Source table: ${table.Name ?? '(unknown)'} — ${draftEntries.length} rows\n` +
  `// Effects mapping pending: see extraction/out/cards.extracted.json\n` +
  `export const CARD_REGISTRY = {\n${draftBody}\n};\n`,
);

console.log(`Rows processed: ${draftEntries.length}`);
console.log(`Wrote ${extractedPath}`);
console.log(`Wrote ${draftPath}`);
console.log('Next: feed cards.extracted.json back into a Claude session to design the effects mapping.');
